export const GET_OFFERS = "GET_OFFERS"
export const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS"
export const GET_OFFERS_ERROR = "GET_OFFERS_ERROR"

export const GET_SOCIAL_NETWORKS = "GET_SOCIAL_NETWORKS"
export const GET_SOCIAL_NETWORKS_SUCCESS = "GET_SOCIAL_NETWORKS_SUCCESS"
export const GET_SOCIAL_NETWORKS_ERROR = "GET_SOCIAL_NETWORKS_ERROR"

export const GET_PLATFORMS = "GET_PLATFORMS"
export const GET_PLATFORMS_SUCCESS = "GET_PLATFORMS_SUCCESS"
export const GET_PLATFORMS_ERROR = "GET_PLATFORMS_ERROR"

export const GET_CITIES = "GET_CITIES"
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS"
export const GET_CITIES_ERROR = "GET_CITIES_ERROR"

export const GET_BLOGGER_DEALS = "GET_BLOGGER_DEALS"
export const GET_BLOGGER_DEALS_SUCCESS = "GET_BLOGGER_DEALS_SUCCESS"
export const GET_BLOGGER_DEALS_ERROR = "GET_BLOGGER_DEALS_ERROR"