export const GET_SOCIAL_NETWORKS = "GET_SOCIAL_NETWORKS"
export const GET_SOCIAL_NETWORKS_SUCCESS = "GET_SOCIAL_NETWORKS_SUCCESS"
export const GET_SOCIAL_NETWORKS_ERROR = "GET_SOCIAL_NETWORKS_ERROR"

export const GET_AD_INFO = "GET_AD_TYPES"
export const GET_AD_INFO_SUCCESS = "GET_AD_TYPES_SUCCESS"
export const GET_AD_INFO_ERROR = "GET_AD_TYPES_ERROR"