export const AUTH_USER = "AUTH_USER"
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS"
export const AUTH_USER_ERROR = "AUTH_USER_ERROR"

export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"