export const GET_ADVERTISER_OFFERS = "GET_ADVERTISER_OFFERS"
export const GET_ADVERTISER_OFFERS_SUCCESS = "GET_ADVERTISER_OFFERS_SUCCESS"
export const GET_ADVERTISER_OFFERS_ERROR = "GET_ADVERTISER_OFFERS_ERROR"

export const GET_ADVERTISER_DEALS = "GET_ADVERTISER_DEALS"
export const GET_ADVERTISER_DEALS_SUCCESS = "GET_ADVERTISER_DEALS_SUCCESS"
export const GET_ADVERTISER_DEALS_ERROR = "GET_ADVERTISER_DEALS_ERROR"